name: Docs Publish CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'docs/**'
      - 'website/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install npm@7
        run: npm i -g npm
      - name: Install Website Dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: website
      - name: Build Application
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: ${{ github.event.head_commit.message }}
